# Generated by Django 3.1.7 on 2021-04-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indonesia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='batubara2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pemasok', models.TextField()),
                ('NilaiKalor', models.CharField(max_length=20)),
                ('TotalMoisture', models.TextField()),
                ('TotalSulfur', models.CharField(max_length=20)),
                ('KadarAbu', models.CharField(max_length=20)),
                ('Potensislagging', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='batubara',
            new_name='batubara1',
        ),
    ]
