# Generated by Django 3.1.7 on 2021-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indonesia', '0003_auto_20210411_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='batubara2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pemasok', models.CharField(max_length=200)),
                ('NilaiKalor', models.IntegerField(null=True)),
                ('TotalMoisture', models.CharField(max_length=200)),
                ('TotalSulfur', models.CharField(max_length=200)),
                ('KadarAbu', models.CharField(max_length=200)),
                ('PotensiSlagging', models.IntegerField(null=True)),
            ],
        ),
    ]
